# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e17e7e6a00d6e40dff6441d41e9c3fe2d3db7328637fd4cf613571c5c0a84e5f9606aea2771853a71dc786c61c5d19cbc37608538279e8f1a10cd90a261ef3f4

test:
  secret_key_base: 514476a855f1476b99cc3b234d14a18137b974e25705fa481dc770974516e6838ef6bb2d5741c8f56d7d19319ab634fa08a897c88f114511c35534f026d33adf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
