# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 307c7ba9257de2550a8725bfa93d4629258601ebc6b12300898f6dd0d489a43f2d661bf274a36ed63cee42a1d4165764fa9b72f77e16e07e984687571725a7f8

test:
  secret_key_base: ab18b3e74439cef82c7dca6ef2641fafd8973e6568654dc81f6e0256a40095ca23abd2747ee36f6deb51d46f5c6d959e1f464e230c850fbb47f2c4c9151936b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
