# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fd946305c515274cda0faa5b462c09634d606453573c2b5e5ee91d4646d050c1ae6f51ce4b8233d4ba51d3abdb389370f9aaf5b37122e2bd0b0c0c454e85840

test:
  secret_key_base: 45c665a221b86ea13bd7cf89066caeac6011882018908f9537339832bb38266a69f50028d2fabc18a677ed1ef5158423a8cdb36a3ee8eeb9b541829667e3fc97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
